### ISSUE TITLE
源失效了

### ISSUE THREAD

**Issue by wanglihui** [OpenGG/bj-unicom-iptv#1]

**Comment by OpenGG** [comment]
My subscription of Unicom internet service has expired. So I can neither update the channel list, nor check its availability.

However the [playlist builder](https://opengg.github.io/bj-unicom-iptv/) still works, you will have to do some extra pasting with the `Custom channels HTML` button.

Even better, You can help others with a pull request. Please check the contribute guide in readme.

**Comment by sdhzdmzzl** [comment]
没失效啊，我这还能播放，除了几个测试频道无法播放外。

**Comment by OpenGG** [comment]
项目停止维护，参考
https://gist.github.com/sdhzdmzzl/93cf74947770066743fff7c7f4fc5820
https://github.com/wuwentao/bj-unicom-iptv
