### ISSUE TITLE
新增cctv4hd

### ISSUE THREAD

**Issue by hcder** [OpenGG/bj-unicom-iptv#2]
239.3.1.105:8092

**Comment by OpenGG** [comment]
Please make a pull request.
Check [the contribute guide](https://github.com/OpenGG/bj-unicom-iptv#contribute-guide).

**Comment by OpenGG** [comment]
项目停止维护，参考
https://gist.github.com/sdhzdmzzl/93cf74947770066743fff7c7f4fc5820
https://github.com/wuwentao/bj-unicom-iptv
