### ISSUE TITLE
我是通过组播扫描工具扫出来的地址，请问如何提pr？

### ISSUE THREAD

**Issue by sdhzdmzzl** [OpenGG/bj-unicom-iptv#3]

**Comment by OpenGG** [comment]
1. 抓包频道列表HTML: 见 [常见问题#3](https://m.newsmth.net/article/DigiHome/757772?p=1))
1. 保存抓包结果为文件 *"iptv.txt"*
1. 检查文件内容是否正确:

    * 打开 [online builder](https://opengg.github.io/bj-unicom-iptv/)
    * 点击 "Custom channels HTML" 按钮
    * 在弹出的输入框中粘贴 *"iptv.txt"* 的内容, 然后点击 "confirm"
    * 下载构建好的m3u播放列表, 检查是否工作正常

1. 如果工作正常, 提交PR:

    * Fork 然后 clone 这个项目
    * 把 *"iptv.txt"* 放入 `public/`
    * 运行 `git add . && git commit -m "Update iptv.txt" && git push`
    * 在 github 网站上发起Pull request

**Comment by sdhzdmzzl** [comment]
我的意思是我没有抓包，而是用软件发包订阅然后监听是否有数据这种方式来扫描出来的地址。所以没有抓包拿到的那个有频道列表的抓包内容。

BTW：有个群友抓了个包给我了一份，不过里边的地址是239.2.1网段的，得手动改成239.3.1网段才可以用。怀疑北京联通针对不同的区域或者不同的机顶盒用了不同的组播地址？

**Comment by bl-knight** [comment]
我这里也是239.2.1的，且有一些地址不能用，比如中央一台HD，我想要一个标准的东西

**Comment by OpenGG** [comment]
项目停止维护，参考 
https://gist.github.com/sdhzdmzzl/93cf74947770066743fff7c7f4fc5820 
https://github.com/wuwentao/bj-unicom-iptv
