### ISSUE TITLE
关于北京联通IPTV的完美方案

### ISSUE THREAD

**Issue by qwertccc** [OpenGG/bj-unicom-iptv#4]
https://exp.newsmth.net/topic/357dabb5a4dc6d5c4c75f96a30209cd9/1

同北京联通，我说一下我本地的环境和问题……

光猫是8347r，我已经改了桥接了，然后登陆的账户密码记不住了，现在我自己也登不上去…地址是192.168.1.1

主路由wan接光猫lan1，pppoe拨号，lan是192.168.2.1

副路由wan接光猫lan4，wan静态地址到192.168.1.4，lan是192.168.123.1

副路由刷Padavan，开iptv组播路由到内网，开udpxy，端口8012

副路由lan1接iptv盒子，盒子正常使用

pc无线连入副路由，播放软件可以看，地址比如http://192.168.1.4:8012/rtp/239.3.1.171:8000或rtp://239.3.1.171:8000都可以

**pc无线连入主路由，播放软件都不可以看，ping不通192.168.1.1和192.168.1.4**

主路由副路由均关闭防火墙，现在就是在主路由下的设备，访问不到副路由

，，，，，，，，，咋整呀。。。。。。。。。。

**Comment by qwertccc** [comment]
光猫里的配置文件我telnet弄出来了

<X_HW_WebUserInfoInstance InstanceID="1" UserName="user" Password="2fd550116b9b5c388bc662ca573df029277c7bfc4371dccac6835478********" UserLevel="0" Enable="1" ModifyPasswordFlag="0" PassMode="3" Salt="1cbcf1ccae829abb********"/>

这可如何是好……密码还不是明文的，还是加密的

不过我找朋友弄了一份他原版系统的配置，其中这部分字段如下

<X_HW_WebUserInfoInstance InstanceID="1" UserName="user" Password="********" UserLevel="1" Enable="1" ModifyPasswordFlag="0"/>

我看这个密码应该是明文的，我琢磨替换过去，然后问题又来了，telenet我上去之后，怎么把修改密码之后的配置文件复写进去……

**Comment by qwertccc** [comment]
UserLevel 这个应该是控制账户级别的，0应该是管理员，1应该是user，其他位置

但是主要现在这玩意儿吧……加密是什么玩意儿，还加盐了……

**Comment by qwertccc** [comment]
恢复原厂后拿到权限了……

光猫的防火墙是关闭的，别的我也不知道该调整哪里了，目前总归连入主路由以后就没办法访问副路由

我干脆……我把光猫从桥接改为拨号了，然后主路由wan设置静态，光猫设置dmz到主路由，主路由再开upnp

折腾了一天…可以安眠了……

**Comment by qwertccc** [comment]
自问自答自锁……

**Comment by OpenGG** [comment]
看这个拓扑图
http://m.newsmth.net/article/DigiHome/833031

**Comment by qwertccc** [comment]
> 看这个拓扑图
> http://m.newsmth.net/article/DigiHome/833031

恍然大悟……
